version: '2'
services:
    vreumester-app:
        image: vreumester
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://vreumester-postgresql:5432/vreuMester
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vreumester-postgresql:
        extends:
            file: postgresql.yml
            service: vreumester-postgresql
